// Companion Action Types
export const ADD_COMPANION_DATA = "ADD_COMPANION_DATA";
export const RESET_ADD_COMPANION = "RESET_ADD_COMPANION";
export const GET_ALL_COMPANIONS = "GET_ALL_COMPANIONS";
export const UPDATE_COMPANION_DATA = "UPDATE_COMPANION_DATA";
export const RESET_UPDATE_COMPANION = "RESET_UPDATE_COMPANION";
export const DELETE_COMPANION = "DELETE_COMPANION";
export const EYESHOW_COMPANION = "EYESHOW_COMPANION";

// User Action Types
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SEARCH_USERS = "SEARCH_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_MORE_USERS = "GET_MORE_USERS";

// Reel Action Types
export const ADD_REEL_DATA = "ADD_REEL_DATA";
export const RESET_ADD_REEL = "RESET_ADD_REEL";
export const UPDATE_REEL_DATA = "UPDATE_REEL_DATA";
export const RESET_UPDATE_REEL = "RESET_UPDATE_REEL";
export const GET_ALL_REELS = "GET_ALL_REELS";
export const DELETE_REEL = "DELETE_REEL";
export const EYESHOW_REEL = "EYESHOW_REEL";

// Feedback Action Types
export const GET_ALL_FEEDBACK = "GET_ALL_FEEDBACK";
export const GET_ALL_REEL_REPORTS = "GET_ALL_REEL_REPORTS";

// Gallery Action Types
export const GET_GALLERY_IMAGES = "GET_GALLERY_IMAGES";
export const UPLOAD_GALLERY_IMAGES = "UPLOAD_GALLERY_IMAGES";
export const DELETE_GALLERY_IMAGE = "DELETE_GALLERY_IMAGE";
export const DELETE_MULTIPLE_GALLERY_IMAGES = "DELETE_MULTIPLE_GALLERY_IMAGES";

// Pagination Settings
export const SET_COMPANIONS_PAGINATION = "SET_COMPANIONS_PAGINATION";
export const SET_REELS_PAGINATION = "SET_REELS_PAGINATION";

// Live Mode Action Types
export const GET_LIVE_MODE = "GET_LIVE_MODE";
export const UPDATE_LIVE_MODE = "UPDATE_LIVE_MODE";
